cyberark/conjur-puppet

.pmtignore
CHANGELOG.md
DEVELOPMENT.md
Dockerfile
Gemfile
README.md
Rakefile
examples/init.pp
metadata.json
release.sh
secrets.yml
spec/fixtures/manifests/init.pp
test/scenario1.pp
test/scenario2.5.pp
test/scenario2.pp
test/scenario4.pp

I also fixed several linting errors that were bringing down our score on Puppet Forge.

Add release.sh script to upload module to Puppet Forge [CON-3929]

---

Rakefile
lib/facter/conjur.rb
lib/puppet/functions/conjur/client.rb
lib/puppet/functions/conjur/netrc.rb
manifests/init.pp
smoketest.sh
spec/classes/init_spec.rb

Store configuration and identity

---

README.md

Document the Conjur fact

---

.fixtures.yml
CHANGELOG.md
README.md
examples/ee/scenario1.pp
examples/ee/scenario2.pp
lib/conjur/puppet_module/config.rb
lib/conjur/puppet_module/identity.rb
lib/facter/conjur.rb
lib/puppet/functions/conjur/client.rb
lib/puppet/provider/credential/wincred.rb
lib/puppet/type/credential.rb
lib/wincred/conversion.rb
lib/wincred/native.rb
lib/wincred/wincred.rb
manifests/config/files.pp
manifests/config/registry.pp
manifests/identity/files.pp
manifests/identity/wincred.pp
manifests/init.pp
manifests/params.pp
metadata.json
spec/classes/init_spec.rb
spec/functions/conjur_secret_spec.rb
spec/functions/conjur_token_spec.rb
spec/unit/conjur_spec.rb
spec/unit/puppet_client_spec.rb

'conjur' class establishes identity for Windows servers

---

CHANGELOG.md
DEVELOPMENT.md
Jenkinsfile
metadata.json

This PR updates the module version to `2.0.0` and adds a pipeline stage to Jenkins to release tagged versions to Puppet Forge.

Release 2.0.0 module

---

CONTRIBUTING.md
examples/docker-compose.yml
examples/puppetmaster/docker-compose.yml
examples/puppetmaster/smoketest_e2e.sh
examples/smoketest.sh

Update docker-compose admin passwords, passwords in test scripts, and the CONTRIBUTING file.

Update dc passwords

---

CHANGELOG.md
metadata.json

This bumps the version from 2.0.2 to 2.0.3
Connected to #73

Prepare for 2.0.3 release

---

examples/puppetmaster/code/environments/production/manifests/site.pp
examples/puppetmaster/docker-compose.yml
examples/puppetmaster/smoketest_e2e.sh
metadata.json

Our current tests are pretty limited in what they examine so this PR
fixes the more-inclusive smoke test.
Connected to #73

Fix smoketest

---

README.md

Just some clarification points in the README .e.g clarified that the Conjur endpoint needs to be accessible to both the Puppet server and agents.
Connected to #98

Some clarification points in the README

---

README.md

Some workflows were either not documented or underdocumented so this
change adds as much information as we have on possible ways to use it.
Connected to #128

Added better workfow documentation for this module

---

examples/puppetmaster/code/data/common.yaml
examples/puppetmaster/code/data/nodes/node01.us.cyber-ark.com.yaml
examples/puppetmaster/code/hiera.yaml
examples/puppetmaster/docker-compose.yml
examples/puppetmaster/vagrant/.gitignore
examples/puppetmaster/vagrant/0_start_puppet_conjur_servers.sh
examples/puppetmaster/vagrant/1_create_or_power_up_vm.sh
examples/puppetmaster/vagrant/2_install_puppet_agent.sh
examples/puppetmaster/vagrant/4_run_puppet_agent.sh
examples/puppetmaster/vagrant/set_env.sh
examples/puppetmaster/vagrant/utils.sh

- Improves some parts of the E2E vagrant tests to run faster using snapshots
- Fixes use of Hiera paths and configs.
- Adds sample Hiera configs 
Connected to #139 
Connected to #89

Improve vagrant tests pt 1/x

---

CHANGELOG.md
README.md
metadata.json

Bumps the version to 2.0.4, and edits the change log to better describe the user impacts of the included changes.
Connected to #110

Bump version to 2.0.4

---

README.md

- Deprecates support for Conjur EE v4 in READEME
- Adds link to our module on puppetforge
Connected to #163 
Connected to #174

163 deprecated conjur v4

---

spec/unit/conjur/puppet_module/identity_spec.rb

Add unit test for #from_wincred
Connected to #135

Add unit test for #from_wincred

---

CONTRIBUTING.md
NOTICES.txt

This file includes legal notices from linked libraries that we use as
part of this module. Information about how to update this data has been
added as part of this change.
Connected to #103

Added NOTICES file

---

CONTRIBUTING.md
README.md
REFERENCE.md
examples/puppetmaster/code/environments/production/manifests/site.pp
gen-docs.sh
lib/puppet/functions/conjur/secret.rb

Follows up PR #179 with cleanup of all comments mentioned in it.
Fixes #183

183 code cleanup

---

CHANGELOG.md
README.md

- Adds our changelog for v2.0.6 release to main branch
- Updates our README with deprecations from `v2` branch
Connected to #180

180 Cherry-pick v2 deprecations

---

CHANGELOG.md
README.md
metadata.json

- Updates the CHANGELOG and metadata for `3.0.0-rc2` pending release.
- Adds a few more tags to metadata to match us with the Ansible module

199 Prepare for `3.0.0-rc2` release

---

Jenkinsfile

* Removes explicit git tag fetch as Jenkins fetches tags automitcally
* Replaces the `agent` call to allocate a windows node with a `node` call. This is because agent allocates a node then automatically clones the git repo under test. However git has proven to be unreliable on windows nodes, and only a single file is required from a public repo, so its easy enough to fetch it via http.
conjurinc/ops#682

Use node instead of agent to avoid auto git checkout

---

CHANGELOG.md
README.md
metadata.json

CHANGELOG was compressed to show only v2->v3 changes and metadata was
updated to refer to the v3 non-RC version.
Connected to #219

Prep for v3.0.0 release

---

README.md
TROUBLESHOOTING.md

This change will allow users to have an easier time debugging issues
with this module as we will have enumerated some of the most common
failure scenarios.
Connected to #120

Added troubleshooting information to documentation

---

CHANGELOG.md
README.md
metadata.json

- Bumps the version of the module to 3.1.0 
- Documents that we are now "certified"
Resolves #240

240 Prep 3.1 release

---

Jenkinsfile

**NOTES:**
1. The build was failing on attempting to fetch a file via http with the following error. (see https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur-puppet/detail/fix/1/pipeline/48)
```
[2021-01-25T15:56:52.845Z] powershell.exe : Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
[2021-01-25T15:56:52.845Z] At C:\jenkins\workspace\cyberark--conjur-puppet_fix@tmp\durable-04aa52cf\powershellWrapper.ps1:3 char:1
[2021-01-25T15:56:52.845Z] + & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
[2021-01-25T15:56:52.845Z] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2021-01-25T15:56:52.845Z]     + CategoryInfo          : NotSpecified: (Invoke-WebReque...secure channel.:String) [], …
```

fix: use stash/unstash for expose-daemon.ps1 instead of fetching via http

---

Jenkinsfile
ci/parse-changelog.sh

- updates Jenkins pipeline to utilize parseChangelog tool
CHANGELOG update
changes, or

Updated Jenkins pipeline to use parseChangelog utility

---

CHANGELOG.md
NOTICES.txt
REFERENCE.md
examples/puppetmaster/code/environments/production/manifests/site.pp
lib/puppet/functions/conjur/secret.rb
lib/puppet/type/credential.rb
metadata.json

Release v3.1.1
- Updated changelog and version numbers
- Regen REFERENCE.md

Bump version to 3.1.1
