cyberark/conjur-puppet

- examples/docker-compose.yml
- examples/smoketest.sh
- Keep going on a failure and only error out at the end.
- Use registry v2 in docker-compose.yml.
- Use unique compose project names to prevent clobbering.
> More robust smoke test script

- lib/conjur/puppet_module/identity.rb
- lib/puppet/provider/credential/wincred.rb
- lib/wincred/wincred.rb
- spec/unit/wincred/wincred_spec.rb
This PR updates how Conjur Puppet encodes the credential values stored in the Windows Credential Manager to use the same encoding (`utf-16le`) that the Windows Cred Manager UI and CLI uses.
This allows the Conjur Puppet integration to read credentials created manually, and not only credentials created by Conjur Puppet directly.
> Encode API as UTF-16LE to match how Windows UI stores them

- examples/smoketest.sh
- manifests/init.pp
- spec/classes/init_spec.rb
Also add some tests and modify a smoke test to cover this case.
Fixes #17.
> Allow using slashes in host names with host factory

- lib/conjur/puppet_module/identity.rb
- lib/puppet/provider/credential/wincred.rb
This PR updates the puppet module to make sure that when string values are given to Puppet, that they are UTF-8 encoded. Otherwise Puppet fails to compare the string values propertly.
> Ensure puppet receives strings encoded as UTF-8

- Gemfile
- release.sh
This PR corrects 2 issues in the release step for Jenkins:
- Removes the `-it` flag from the Docker command to fix "No TTY" error in Jenkins
- Updates 'puppet-blacksmith' version to fix RestClient OpenSSL `:cipher` key error
> Fix Release Script Errors

- metadata.json
Puppet 5 is the requirement for Conjur Puppet 2.0.0, however there is a bug (#44) preventing full operation with Puppet 6.
This PR updates the module manifest to indicate support for Puppet 5 only.
> Update Puppet version requirements

- CHANGELOG.md
- metadata.json
The 2.0.0 module on Puppet Forge cannot be replaced, so push this as a new version.
> Bump version to 2.0.1

- examples/docker-compose.yml
- examples/puppetmaster/docker-compose.yml
- examples/puppetmaster/smoketest_e2e.sh
- examples/smoketest.sh
Since most users will setup their servers this way, it was valuable that
we do it too in that manner. With this change, we are also working around
a bug in Conjur that prevents CIDR resources from being properly loaded
through the `conjurctl` command: https://github.com/conjurinc/dap-support/issues/80
Connected to #61
> Changes smoketests to use CLI to set initial policy

- CHANGELOG.md
- lib/puppet/functions/conjur/client.rb
- spec/functions/conjur_secret_spec.rb
Connected to #72 
Variable IDs were not encoded at all so in case a user had
a variable with spaces in it, we were not able to retrieve it.
The encoding method we use now encodes spaces into "%20" as required
by the Conjur v5 server. It also encodes slashes into "%2F" as required.
This commit updates the current UTs to expect "%2F" for slashes instead of
actual slashes (both are accepted in the server) and adds a UT for a variable
that has spaces in its name.
This PR doesn't change the behaviour for Conjur v4 as I am not sure what the expected behaviour is. In case there was an error with spaces it is still there. However, as the behaviour didn't change then this PR doesn't add any new errors.
> Properly encode spaces in variable names for Conjur v5

- Jenkinsfile
- examples/puppetmaster/docker-compose.yml
- examples/puppetmaster/smoketest_e2e.sh
This should allow us to find errors that our old tests did not as they only
run with a self-contained local agent.
> Include e2e test in build

- examples/ee/puppetmaster/docker-compose.yml
- examples/ee/smoketest.sh
- examples/puppetmaster/docker-compose.yml
- examples/smoketest.sh
- Removes no longer available `puppet/puppet-agent-centos`, `puppet/puppet-agent-debian`, and `puppet/puppetdb-postgres` images from use in the repo
- Adds `puppet/puppet-agent-alpine` as a test case
> Fix currently-broken build

- CHANGELOG.md
- README.md
- examples/puppetmaster/docker-compose.yml
- examples/puppetmaster/smoketest_e2e.sh
- lib/facter/conjur.rb
- Fixes CA chain retrieval on agents to use both v6 and v5 compatible method
- Adds more test cases to E2E smoketest
Connected to #44
> 44 Fix puppet v6 client methods for CA chain retrieval

- CHANGELOG.md
- Jenkinsfile
- README.md
- examples/puppetmaster/docker-compose.yml
- examples/puppetmaster/smoketest_e2e.sh
- lib/puppet/functions/conjur/decrypt.rb
- Fixes use of missing APIs for token decryption in v6 server
- Expands the test matrix to test v6 with e2e tests
Connected to #91
> 91 Fix token decryption in v6 server

- README.md
- Adds back in the `conjurize` instructions with a big `Conjur v4 only!` caveat (we will deprecate this, likely at the end of milestone 2)
- Removes v6 support from README, as we're not formally announcing this until the end of [milestone 2](https://github.com/cyberark/conjur-puppet/issues/20)
Note: I also filed https://github.com/cyberark/conjur-puppet/issues/107 to review the supported versions of all agent types and update them before Milestone 2 wraps up.
n/a
> Conjurize lives

- README.md
Previously the doc was pointing to the old Conjur Enterprise v4 site
n/a
> Update HFT link to point to conjur.org

- CHANGELOG.md
- README.md
- lib/conjur/puppet_module/config.rb
- manifests/init.pp
+ Add support for `cert_file` on Windows and to the `conjur` class
+ Update README with description and examples of `cert_file`
Connected to #113
> Add support for `cert_file` on Windows

- CHANGELOG.md
- lib/conjur/puppet_module/config.rb
- lib/conjur/puppet_module/identity.rb
- Fixes issues with persisting/retrieving HFT-based credentials on Windows hosts (#47)
- Fixes issues on hiera-provisioned HFT-based Windows hosts where a missing registry key was throwing exceptions (#112)
- Adds better logging to Windows-based config/credential fetching
- Adds warnings to missing *nix identities on agents
Connected to #47
Connected to #112
> 47 HFT WinCred persistence bug

- Gemfile
There were upstream issues with broken dependencies that we upstreamed a
fix for and because of this we needed to pin to latest (unreleased)
version of `rspec-puppet` gem. In the process, it seems like we also
discovered that our fork was not required as the tests all pass so it
was likely that we just had a fork to have a pre-release features ready
which are now in mainline.
Upstream bug: https://github.com/rodjek/rspec-puppet/issues/796
Upstream fix: https://github.com/rodjek/rspec-puppet/pull/797
Connected to #132
> 132 Fix build upgrades and remove `rspec-puppet` fork dependency

- Dockerfile
- Gemfile
- Jenkinsfile
- docker-compose.test.yml
- test.sh
Our testing previously only tested against v5 puppet gem and was not a
reliable source of truth towards its fucntionling with puppet v6. This
change now allows `./test.sh` to run both varieties of the versions in
parallel.
N/A
> Made unit tests run against both Puppet v5 and v6 gems

- README.md
s/hosts/host. Hosts in Conjur come with a `host` prefix not `hosts`.
Update README.md
Note that when following the previous instructions you end up in a situation where you have the wrong hostname `hosts/node01` which results in an Unauthorized error when an attempt to retrieve the token is made. In the logs of the agent  you get this pretty unhelpful error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Method call, 'conj
ur::token' parameter 'key' expects a Sensitive[String] value, got Undef (file: /etc/puppetlabs/code/environments/production/modules/conjur/manifests/i
nit.pp, line: 42, column: 35) on node c22611896ec1
```
If you happen to be running the agent in debug mode you might noticed several …
> Update windows cred example in README.md

- README.md
- examples/puppetmaster/smoketest_e2e.sh
This change adds a warning to the main conjur-puppet README.md file that
the Conjur identity files `conjur.conf` and `conjur.identity` must have
their file permissions set to `600` when these files are manually
configured (pre-provisioned) on a Linux node. This is needed to prevent
access to the sensitive information contained in these files by
unauthorized users on a Linux Puppet agent node.
This change also includes a modification to the
`examples/puppetmaster/smoketest_e2e.sh` script such that the file
permissions for the Conjur identity files for this smoketest are properly
set to `600`.
Addresses Issue #143
- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can …
> Adds warning to set Conjur identity file permissions to 600

- lib/conjur/puppet_module/config.rb
The error wording was overall not accurate and in many cases not overly
useful so now we clearly specify that this is something that only
happens on server-provided credentials and the warning has been dialed
down to a notice since this is more common than node-provided
authentication.
Connected to #149
> 149 Fix agent's missing registry entries warning on Windows agents

- CHANGELOG.md
- README.md
Clean up and clarify cert_file references in README. It also highlights that all `cert_file` values result in a file being read from the Puppet server and only the Windows registry value named `CertFile` results in a file being read from the Puppet agent.
Add section detailing machine identity persistence in README
#148  #152
> Clarify cert_file references and machine identity persistence, and clean up README.md

- README.md
Adds a bolded warning to the README.md file that if Conjur connection
information is configured in the Windows Registry for a Puppet agent
node, then care must be taken to ensure that non-administrator users
do not have write permissions for these Conjur connection Windows
Registry entries.
Fixes Issue #142
- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_
Connected to #[relevant GitHub issues, eg 76]
> Adds warning that std users must not have write access to WinReg config

- manifests/config/files.pp
- manifests/config/registry.pp
- manifests/init.pp
Puppet variables are immutable once set. To allow the runtime ssl_certificate to be populate by either the ssl_certificate param or cert_file param we need a separate variable that will be consumed at runtime.
Connected to #156
> Store runtime ssl_certificate in raw_ssl_certificate for conjur class

- manifests/config/files.pp
- manifests/config/registry.pp
- manifests/init.pp
Reverts cyberark/conjur-puppet#157 - we are mid-release cycle for v2.0.4 and are going to hold off on this bug fix until the next version.
Note: this means that #147 and #156 are both outstanding bugs relating to `cert_file` in the v2.0.4 release, so we recommend users continue to use `ssl_certificate` in v2.0.4.
> Revert "Store runtime ssl_certificate in raw_ssl_certificate for conjur class"

- Gemfile
- Jenkinsfile
- Rakefile
- build.sh
- test.sh
Reverts the Puppet gem in the build pipeline to v5.x to enable publishing. Makes additional minor changes to enable building the module locally.
n/a
> Updates to enable building and publishing the v2.0.4 module

- CHANGELOG.md
- README.md
- metadata.json
- Largely removes `cert_file` from README until it can be added back in the solution to #147 and #156 
- Bumps version in preparation for next tag
Connected to #163
> Bump version 2.0.5

- CHANGELOG.md
- lib/facter/conjur.rb
- lib/puppet/functions/conjur/client.rb
- spec/functions/conjur_secret_spec.rb
- spec/functions/conjur_token_spec.rb
- spec/unit/puppet_client_spec.rb
Since Conjur v4 is deprecated we can ssafely remove support for this API
version from the code. In the process, some of the code is simplified,
though we left the "version" variable to be able to forward-support
higher versions of the API.
Connected to #66
> 66 Remove out Conjur EE v4 support from code

- CHANGELOG.md
- README.md
- REFERENCE.md
- examples/puppetmaster/code/environments/production/manifests/site.pp
- examples/puppetmaster/test.sh
- lib/puppet/functions/conjur/secret.rb
- spec/functions/conjur_secret_spec.rb
Since positional parameters are both hart to use and consistently get
correct without documentation, this change ensures that we use a hash
instead which will allow better UX and possibly enable use of partial
overrides.
Connected to #184
> 184 Converted positional params to `conjur::secret` to a hash

- CHANGELOG.md
- README.md
- metadata.json
Since we will support neither Puppet 5 nor HFTs in the next major
release, this change documents that these features are now deprecated
in v2 branch of the module. Version is bumped to v2.0.6 in preparation
for publishing this change.
Connected to #180
> 180 Deprecate HFTs and Puppet 5 in v2

- Jenkinsfile
This will make sure that publishing of tags only occurs when the source
branch is either `v2` or `master` as we should not have any other
sources of publishable artifacts.
N/A
> Limit publishing to v2 and master branches only

- Jenkinsfile
This reverts commit 75aa90ad32a5474e1f9df39fb1e6edd518dcf4fc.
Since tags are built in separate builds with no parent branch, this
change did not work as expected. As such, it will need to be reverted
until we find a better way to lock down the tag's parent branch.
N/A
> Revert "Limit publishing to v2 and master branches only"

- .dockerignore
- .gitignore
- Gemfile
- Jenkinsfile
- spec/spec_helper.rb
- Adds code coverage metrics to Jenkins
- Pins current coverage metrics as minimums for code coverage
See https://jenkins.conjur.net/job/cyberark--conjur-puppet/job/194-add-code-coverage-metrics/ for output
Connected to #194 
Connected to #121
> 194 Add code coverage metrics

- build.sh
- examples/puppetmaster/docker-compose.yml
- examples/puppetmaster/test.sh
- _What's changed? Why were these changes made?_
The envvar INSTALL_PACKAGED_MODULE has been added to the E2E tests and allows developers to toggle between installing a packaged module or using the module source. The default (which is used by CI) is to install the packaged module.
- _How should the reviewer approach this PR, especially if manual tests are required?_
N/A
- _Are there relevant screenshots you can add to the PR description?_
N/A
Connected to #173
> E2E tests install the packaged module by default

- Jenkinsfile
Old version of the logic was only capable of handling `vxx.yy.zz` tag
pattern. This change makes it so that we can also push pre-release
semver tags too.
- Allows publishing from pre-release tags
> Made Jenkinsfile release step match on pre-release tags too

- Jenkinsfile
- release.sh
This change ensures that we do not consent to collection of analytics
and that we also skip this question during the release of our puppet
module.
- Use of PDK analytics has been disabled
> Disable PDK analytics

- examples/puppetmaster/code/environments/production/manifests/site.pp
- examples/puppetmaster/policy.yml
- examples/puppetmaster/test.sh
- examples/puppetmaster/vagrant/5_get_puppet_artifacts.sh
While we have a few unit tests around this, having a solid integration
test for odd characters in the ID will ensure that we do not get odd
behaviour when interacting with a rela Conjur server.
- Makes Linux and Windows integration testing also use a variable with special characters in ID
Connected to #79
> 79 Add integration test for use of special chars in variable ID

- .pdkignore
Since PDK may use this directory for caching, we don't want its content
to polute our artifacts so it has been added to `.pdkignore`.
> Ignore `.pdk` directory when building artifacts

- release.sh
- secrets.yml
Since PDK only uses the API key and not the user/pass combo, we now have
to use this new credential in our release script.
~Blocked by https://github.com/conjurinc/conjurops-policies/pull/139~
> Use PuppetForge API key to publish the release

- release.sh
Due to the way the shell scriptis used, we needed to escape the variable
name for it to be interpreted within the container itself.
> Fixed escaping of PDK token during releases

- .dockerignore
- .pdkignore
- CHANGELOG.md
`cc-test-reporter`, `.cache`, and `.DS_Store` are inadvertently included
into our build artifacts by Jenkins and local builds, bulking up the artifact
size significantly. This change ensures that these files are excluded.
Connected to #213
> Exclude unnecessary files from release artifacts

- README.md
Since `SslCertificate` has newlines, it cannot be
set using a registry file so we clear this up in the README now.
N/A
> Document fact that SslCertificate cannot be set via registry file

- examples/puppetmaster/test.sh
This PR adds a fix for the following error:
```
Error: Failed to apply catalog: Unknown function 'conjur::secret'
```
that is seen when running the examples/puppetmaster/test.sh locally.
- Makes sure that the Conjur modules directory that is the target of a
symlink is cleared before doing the symlink. Without this change,
the symlink was creating a nested conjur target (...conjur/conjur).
- Makes sure the parent `module` directory exists for the symlink
target.
Connected to #[relevant GitHub issues, eg 76]
> Fix unknown function error for running examples/puppetmaster locally

- Jenkinsfile
- gen-docs.sh
- lib/puppet/type/credential.rb
Old code wasn't using the exact specification for custom types and would
thus fail to generate the documentation. The change just makes sure that
we use the proper construct which makes the process correctly generate
the reference documentation.
Connected to #166
> Fix problems with using `puppet strings` on the codebase

- CHANGELOG.md
- README.md
- REFERENCE.md
- lib/puppet/functions/conjur/secret.rb
Old documentation did not go into necessary depths to ensure that the
user was provided with all the necessary information about how the
`Deferred` and `Sensitive` chaining work and why they are critical in
ensuring secure use of credentials. This PR ensures that we do that and
fixes some outdated examples.
Connected to #198
> Heavily document `Sensitive` and `Deferred` requirements

- Jenkinsfile
- examples/puppetmaster/code/environments/production/manifests/site.pp
- examples/puppetmaster/test.sh
- examples/puppetmaster/windows-agent.Dockerfile
- expose-daemon.ps1
+ Add ability to integration tests against Windows environment
Integration testing against puppet agents running on Windows is possible and configurable. Export the WINDOWS_DOCKER_HOST envvar to enable the Windows tests. The configurable options are available as envvars WINDOWS_DOCKER_HOST, WINDOWS_DOCKER_CERT_PATH, WINDOWS_DOCKER_TLS_VERIFY, MAIN_HOST_IP. MAIN_HOST_IP is the IP address of the host where the tests are running that should be accessible from containers running in the Windows Docker Daemon.
+ Add Windows node to integration tests in Jenkins
Adds a Windows 2016, with containers, node to the pipeline using the parallel stages approach for cooperation between Jenkins nodes. This provides a Windows Docker daemon for the integration tests to use
Here's an example of a run where …
> Integration test against Windows environment

- examples/puppetmaster/docker-compose.yml
- examples/puppetmaster/test.sh
This change adds a compilation master and makes the agent E2E tests use
it. This change should ensure that our plugin works in large and
extra-large deployments of Puppet infrastructure.
Connected to #209
> Added compiler master to E2E tests

- CHANGELOG.md
- README.md
- REFERENCE.md
- lib/conjur/puppet_module/config.rb
- lib/puppet/functions/conjur/secret.rb
- spec/functions/conjur_secret_spec.rb
- spec/unit/conjur/puppet_module/config_spec.rb
While support for this parameter was partially in the codebase, the
documentation was lacking and we didn't have good unit tests around
this. This change ensures that we have this capability tested and
documented just as much as the other features.
Connected to #105
> Finish support for `cert_file` parameter

- CHANGELOG.md
- lib/puppet/functions/conjur/secret.rb
- spec/functions/conjur_secret_spec.rb
Since we require that the API key be of a Sensitive() type and we did
not have a good error message when the user provided us a value of a
different type, we now show a friendlier message early as to what is
wrong with the passed parameter.
Connected to #232
> Raise better error when authn_api_key is not wrapped in `Sensitive()`

- .rubocop.yml
- CHANGELOG.md
- lib/conjur/puppet_module/http.rb
- spec/unit/conjur/puppet_module/http_spec.rb
We want to notify the user that any communication over non-https links
is insecure so this change adds puppet warnings for any attempt at
accessing such endpoints.
Connected to #144
> 144 Add warning when accessing non-https URLs

- examples/puppetmaster/vagrant/3_run_puppet_agent.sh
Old code was unable to correctly filter multiple containers with
puppetserver image running concurrently so now we ensure that we filter
the resulting containers correctly.
N/A
> Fix running Vagrant tests with compilation masters enabled

- lib/conjur/puppet_module/http.rb
- spec/unit/conjur/puppet_module/http_spec.rb
This will enable us to make POST requests that require authorization.
Even though it's not currently used, it will enable us to invoke API
endpoints that we were not able to use before.
Connected to #200
> Add ability to pass in authentication token in POST requests

- CHANGELOG.md
- TROUBLESHOOTING.md
- lib/conjur/puppet_module/http.rb
- spec/unit/conjur/puppet_module/http_spec.rb
This will allow for easier troubleshooting since it will indicate that
the error seen is from the server and not from the conjur module itself.
Resolves #241
> Wrapped HTTP errors from Conjur in a descriptive error

- ci/test.sh
This workaround for cyberark/conjur-puppet/issues/246 uses our
own PDK tool image instead of `puppet/pdk` until upstream issue
https://github.com/puppetlabs/pdk-docker/issues/12 is fixed.
Resolves #246
> Add workaround for broken upstream PDK image

- README.md
- REFERENCE.md
- TROUBLESHOOTING.md
Updating naming for Conjur editions
- converts `Conjur OSS` to `Conjur Open Source`
- converts `DAP`/`Dynamic Access Provider` to `Conjur Enterprise`
- maintains `Conjur OSS Suite` and `Conjur Open Source Suite`
This is part of an automated batch of PRs across many repos listed in [cyberark/community#92](https://github.com/cyberark/community/issues/92)
> Updating naming for Conjur editions

- .gitignore
- CHANGELOG.md
- ci/Dockerfile.pdk
- ci/expose-daemon.ps1
- examples/puppetmaster/code/environments/production/manifests/site.pp
- examples/puppetmaster/test.sh
The version of puppet included with PDK (6.27.0) is broken due to a change in concurrent-ruby. It appears to be fixed in Puppet 6.29.0, so update the dockerfile to fetch a newer version of PDK
See: https://github.com/ruby-concurrency/concurrent-ruby/pull/988
Fixed by: https://github.com/puppetlabs/puppet/pull/8996
Also address dev tasks around updating Docker base images and upgrading to Ruby 3.
- Run `pdk validate` and `test ` against a more recent version of Puppet with the fix
- Update docker base images
- Fix Windows docker builds by disabling buildkit
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or
> Fix bug in PDK validate/test

- CHANGELOG.md
- ci/Dockerfile.pdk
This pull request upgrades ruby from 3.2.1 to ruby 3.2.2. Upgrading to 3.2-slim does not seem to be feasible as it caused the build to fail.
CHANGELOG update
changes, or
> Upgrade ruby to 3.2.2

- CHANGELOG.md
- Gemfile
- Jenkinsfile
- ci/Dockerfile.pdk
- ci/test.sh
- metadata.json
- spec/spec_helper.rb
Fix buidling of the PDK image, and upgrade the Dockerfile base image to 3.3-rc-slim
Includes changes from https://github.com/cyberark/conjur-puppet/pull/257
NOTE: Due to recurring issues with provisioning Windows nodes in CI we are skipping the integration tests for now, but it is highly unlikely that these changes will have impacted the modules functionality.
*At least 1 todo must be completed in the sections below for the PR to be
merged.*
CHANGELOG update
changes, or
> Upgrade ruby base image

- ci/release.sh
The `pdk validate` step in the release process fails on Ruby validation but provides no output:
```
pdk (INFO): Using Ruby 3.2.2
pdk (INFO): Using Puppet 8.1.0
[✔] Installing missing Gemfile dependencies.
pdk (INFO): Validator 'puppet-plan-syntax' skipped for '/conjur'. No files matching '["plans/**/*.pp"]' found to validate.
pdk (INFO): Validator 'puppet-epp' skipped for '/conjur'. No files matching '["**/*.epp"]' found to validate.
pdk (INFO): Validator 'task-name' skipped for '/conjur'. No files matching '["tasks/**/*"]' found to validate.
pdk (INFO): Validator 'task-metadata-lint' skipped for '/conjur'. No files matching '["tasks/*.json"]' found to validate.
┌ [✔] Running metadata validators ...
├── [✔] Checking metadata syntax (metadata.json tasks/*.json).
└── [✔] Checking module …
```
> Skip validate
